---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - 'recipe[canary::default]'
    attributes:
  - name: sensord
    run_list:
      - 'recipe[canary::sensord]'
  - name: canaryd
    run_list:
      - 'recipe[canary::canaryd]'
