name             'canary'
maintainer       'Jeremy Olliver'
maintainer_email 'jeremy.olliver@gmail.com'
license          'apachev2'
description      'Installs/Configures canary'
long_description 'Installs/Configures canary'
version          '0.1.0'

depends 'golang'
depends 'build-essential'
depends 'redisio'
